name: 'snowflake_finops'
version: '1.2.0'
config-version: 2

profile: 'snowflake_finops'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

vars:
  enable_pro_pack: false
  DEMO_MODE: false
  cost_per_credit: "{{ env_var('COST_PER_CREDIT', 3.00) }}"
  query_history_days: "{{ env_var('WINDOW_DAYS', 30) }}"
  metering_history_days: "{{ env_var('WINDOW_DAYS', 30) }}"
  account_usage_database: "SNOWFLAKE"
  account_usage_schema: "ACCOUNT_USAGE"

models:
  on_schema_change: "{{ 'fail' if target.name == 'prod' else 'sync_all_columns' }}"
  snowflake_finops:
    staging:
      +materialized: incremental
      +tags: ["stage:staging","pack:base"]
    intermediate:
      +materialized: incremental
      +tags: ["stage:intermediate","pack:base"]
    marts:
      +materialized: table
      +tags: ["stage:marts","pack:base"]
  