USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FINOPS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FINOPS_DEV;
CREATE SCHEMA IF NOT EXISTS FINOPS_DEV.ANALYTICS;
CREATE DATABASE IF NOT EXISTS FINOPS_PROD;
CREATE SCHEMA IF NOT EXISTS FINOPS_PROD.ANALYTICS;

CREATE ROLE IF NOT EXISTS FINOPS_DBT_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE FINOPS_WH TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON DATABASE FINOPS_DEV TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON DATABASE FINOPS_PROD TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE FINOPS_DEV TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE FINOPS_PROD TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE FINOPS_DEV TO ROLE FINOPS_DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE FINOPS_PROD TO ROLE FINOPS_DBT_ROLE;

-- Required for FINOPS_DBT_ROLE to read SNOWFLAKE.ACCOUNT_USAGE.
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FINOPS_DBT_ROLE;

GRANT ROLE FINOPS_DBT_ROLE TO USER DJM;
ALTER USER DJM SET DEFAULT_ROLE = FINOPS_DBT_ROLE;
ALTER USER DJM SET DEFAULT_WAREHOUSE = FINOPS_WH;
