name: Build & Publish dbt Docs (Base & Pro)

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      DBT_PROFILES_DIR: ./.ci/profiles
      PRO_REPO_TOKEN: ${{ secrets.PRO_REPO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove stale package lock (if any)
        run: rm -f package-lock.yml

      - name: dbt deps (Base only)
        run: dbt deps

      - name: Generate Base docs
        run: >
          dbt docs generate
          --target docs
          --target-path target/base
          --vars '{"enable_pro_pack": false, "DEMO_MODE": true}'
          --exclude 'source:account_usage_backlog.*' tag:backlog

      # --- PRO BLOCK (token-gated) ---
      - name: Enable GitHub token for private packages (Pro)
        if: ${{ env.PRO_REPO_TOKEN != '' }}
        run: git config --global url."https://${PRO_REPO_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Add Pro package & deps
        if: ${{ env.PRO_REPO_TOKEN != '' }}
        run: |
          cp packages.yml packages.base.yml
          printf "\n  - git: https://github.com/mcgrath-dylan/snowflake-finops-pro.git\n    revision: main\n" >> packages.yml
          dbt deps

      - name: Generate Pro docs
        if: ${{ env.PRO_REPO_TOKEN != '' }}
        run: >
          dbt docs generate
          --target docs
          --target-path target/pro
          --vars '{"enable_pro_pack": true, "DEMO_MODE": false, "snowflake_finops_pro": {"enable_pro_pack": true}}'
          --exclude 'source:account_usage_backlog.*' tag:backlog
      # --- END PRO BLOCK ---

      - name: Build static site (index + subdirs)
        run: |
          mkdir -p site/base site/pro
          [ -d target/base ] && cp -r target/base/* site/base/ || true
          [ -d target/pro ] && cp -r target/pro/* site/pro/ || true
          cat > site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>finops-dbt docs</title>
          <style>body{font-family:ui-sans-serif,system-ui,-apple-system;max-width:720px;margin:40px auto;padding:0 16px}a{display:block;margin:12px 0;font-size:18px}</style>
          <h1>finops-dbt — documentation</h1>
          <a href="base/index.html">Base (Starter)</a>
          <a href="pro/index.html">Pro (Starter + Pro Pack)</a>
          HTML

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
