# models/schema.yml  (Starter)
version: 2

models:
  - name: fct_daily_costs
    description: "Daily compute/idle/cloud-services/total cost by warehouse. $$ from metering history; query-level $$ are estimates only."
    config:
      contract:
        enforced: true
    tests:
      - unique:
          column_name: daily_cost_key
    columns:
      - name: usage_date           # ::date
        data_type: date
        tests: [not_null]
      - name: warehouse_name       # ::varchar
        data_type: varchar
        tests:
          - relationships:
              arguments:
                to: ref('stg_warehouse_metering')
                field: warehouse_name
      - name: compute_credits      # ::number(38,3)
        data_type: number
      - name: compute_cost         # ::number(38,2)
        data_type: number
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0}
      - name: cloud_services_cost  # ::number(38,2)
        data_type: number
      - name: total_cost           # ::number(38,2)
        data_type: number
      - name: idle_cost            # ::number(38,2)
        data_type: number
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments: {min_value: 0}
      - name: productive_cost      # ::number(38,2)
        data_type: number
      - name: total_queries        # ::number(38,0)
        data_type: number
      - name: avg_concurrent_users # ::number(38,2)
        data_type: number
      - name: cost_per_query       # ::number(38,4)
        data_type: number
      - name: efficiency_score     # ::number(5,2)
        data_type: number
      - name: month_to_date_cost   # ::number(38,2)
        data_type: number
      - name: cost_7day_avg        # ::number(38,2)
        data_type: number
      - name: day_over_day_change  # ::number(38,2)
        data_type: number
      - name: week_over_week_change # ::number(38,2)
        data_type: number
      - name: daily_cost_key       # surrogate key
        data_type: varchar
      - name: _loaded_at           # cast(current_timestamp() as timestamp_ntz)
        data_type: timestamp_ntz
